#!/bin/bash

export CI_WEB_ROOT=$1
export CI_WEB_RELEASE=$2

mkdir "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}"
ln -sfn "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}" "${CI_WEB_ROOT}current"

rsync -r . "${CI_WEB_ROOT}current"

rm -rf "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}/sites"
ln -s "${CI_WEB_ROOT}shared/sites" "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}/sites"

# TODO: Run some sort of database configuration execution

echo "Branch $CI_COMMIT_REF_NAME (at `git log --pretty=format:'%h' -n 1`) deployed as release ${CI_WEB_RELEASE} by `whoami`" >> "${CI_WEB_ROOT}/revisions.log"

sudo /etc/init.d/nginx reload
sudo /etc/init.d/php7.1-fpm restart
