#!/bin/bash

export CI_WEB_ROOT=$1
export CI_WEB_RELEASE=$2

export CI_SHARED_WEB=${CI_WEB_ROOT}shared/web
export CI_RELEASE_WEB=${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}/web

mkdir "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}"
ln -sfn "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}" "${CI_WEB_ROOT}current"

cp wp-cli.yml "${CI_WEB_ROOT}current"
rsync -r ./config "${CI_WEB_ROOT}current"
rsync -r ./vendor "${CI_WEB_ROOT}current"
rsync -r --exclude-from=".rsync" ./web "${CI_WEB_ROOT}current"

mkdir -p "${CI_WEB_ROOT}shared/web/app"
rm -rf "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}/web/app/uploads"
ln -s "${CI_WEB_ROOT}shared/web/app/uploads" "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}/web/app/uploads"
ln -s "${CI_WEB_ROOT}shared/.env" "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}/.env"

for CI_STATIC_FILE in $(ls -d -1 $CI_SHARED_WEB/*)
do
  ln -s $CI_STATIC_FILE "${CI_RELEASE_WEB}/$(basename "$CI_STATIC_FILE")"
done

pushd "${CI_WEB_ROOT}current"
wp plugin activate --all
popd

echo "Branch $CI_COMMIT_REF_NAME (at `git log --pretty=format:'%h' -n 1`) deployed as release ${CI_WEB_RELEASE} by `whoami`" >> "${CI_WEB_ROOT}/revisions.log"

sudo service nginx reload
