#!/bin/bash

export CI_WEB_ROOT=$1
export CI_WEB_RELEASE=$2

mkdir "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}"
rm -f "${CI_WEB_ROOT}current"
ln -s "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}" "${CI_WEB_ROOT}current"
rsync -r ./config "${CI_WEB_ROOT}current"
rsync -r ./vendor "${CI_WEB_ROOT}current"
rsync -r --exclude-from=".rsync" ./web "${CI_WEB_ROOT}current"
rm -rf "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}/web/app/uploads"
ln -s "${CI_WEB_ROOT}shared/web/app/uploads" "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}/web/app/uploads"
ln -s "${CI_WEB_ROOT}shared/.env" "${CI_WEB_ROOT}releases/${CI_WEB_RELEASE}/.env"

echo "Branch $CI_COMMIT_REF_NAME (at `git log --pretty=format:'%h' -n 1`) deployed as release ${CI_WEB_RELEASE} by `whoami`" >> "${CI_WEB_ROOT}/revisions.log"
